name: PR Build and Test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node.JS ${{ matrix.node-version }} Axios ${{ matrix.axios-version }}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        axios-version: [0.24.0, 0.25.0, 0.26.1, 0.27.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn add -D axios@${{ matrix.axios-version }}
      - run: yarn test
