name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8, 10, 12]
    steps:
      - uses: actions/checkout@v2
      - name: Exit if not on master branch
        if: endsWith(github.ref, 'master') == false
        run: exit 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org
      - name: Build and Test
        run: |
          yarn
          yarn test
          yarn prepare
          yarn coverage
      - name: Exit if not node 8
        if: matrix.node != 8
        run: |
          echo 'Skipping, releasing/coverage report via node 8 build only.'
          exit 0
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .nyc_output/lcov.info
      - name: Publish to Npm
        run: |
          npm publish --access public
        env:
            NODE_AUTH_TOKEN: ${{secrets.LIFEOMIC_NPM_TOKEN}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
